### ISSUE TITLE
Does not type check

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [andrewMacmurray/haskell-book-solutions#21]
https://github.com/andrewMacmurray/haskell-book-solutions/blob/f4fd386187c03828d1736d9a43642ab4f0ec6462/src/ch11/vehicles.hs#L45

**Comment by andrewMacmurray** [comment]
@BebeSparkelSparkel really? Mine compiles and runs fine, is there something specific you did to assert it doesn't type check?

**Comment by BebeSparkelSparkel** [comment]
Now that I'm looking at this more closely it seems that the book may have changed so that `Plane` only has one attribute
```haskell
data Vehicle = Car Manufacturer Price
             | Plane Airline
             deriving (Eq, Show)
```

Thanks for checking on this

**Comment by andrewMacmurray** [comment]
@BebeSparkelSparkel Ah that makes sense, I should probably either add the version of the book I used or update the exercise, cheers for letting me know 👍

**Comment by BebeSparkelSparkel** [comment]
Np you're welcome
